# This action updates the osbuild ref in the Schutzfile
---
name: "Update osbuild commit ID"

on:  # yamllint disable-line rule:truthy
  workflow_dispatch:
  schedule:
    # Every Sunday at 12:00
    - cron: "0 12 * * 0"

jobs:
  update-and-push:
    runs-on: ubuntu-24.04
    env:
      GH_TOKEN: ${{ secrets.SCHUTZBOT_GITHUB_ACCESS_TOKEN }}
    steps:
      - name: Clone
        # This workflow can be started from a branch, but we always want to
        # work on main to update the osbuild ref.
        # WARNING: This means the update-schutzfile-script below will always be
        # run from the main branch.
        run: |
          git clone --depth=1 --branch main https://github.com/$GITHUB_REPOSITORY ./src

      - name: User config
        working-directory: ./src
        run: |
          git config user.name "schutzbot"
          git config user.email "schutzbot@gmail.com"

      - name: Update Schutzfile
        working-directory: ./src
        env:
          # GITHUB_TOKEN is required by the script
          # TODO: change it to read GH_TOKEN for consistency with gh cli
          GITHUB_TOKEN: ${{ secrets.SCHUTZBOT_GITHUB_ACCESS_TOKEN }}
        # script also creates github_pr_body.txt
        run: |
          ./test/scripts/update-schutzfile-osbuild

      - name: Open PR
        working-directory: ./src
        run: |
          if git diff --exit-code; then echo "No changes"; exit 0; fi
          branch="schutzfile-osbuild-$(date -I)"
          git checkout -b "${branch}"
          git add Schutzfile
          git commit -m "schutzfile: Update osbuild dependency commit ID"
          remote="https://oauth2:${GH_TOKEN}@github.com/${GITHUB_REPOSITORY}"
          git push -f "${remote}" "${branch}"
          gh pr create \
            --title "Update osbuild dependency commit ID" \
            --body-file "github_pr_body.txt" \
            --base "main" \
            --head "${branch}"
